version: "3"
services:
    target:
        image: "${TARGET_TAG}"
    test:
        image: "${TEST_TAG}"
        volumes:
          - ${WORK_SPACE}:c:/solution/workspace
        links:
          - target:target
        depends_on:
          - target
        environment:
          COMPOSE_KEEP: ${COMPOSE_KEEP}

networks:
  default:
    external:
      name: nat
